version: '3.1'

services:
  mysqldb:
    image: mysql/mysql-server:5.7
    container_name: mysqldb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD:
    ports:
      - "3306:3306"
    volumes:
      - /home/mysql/data:/var/lib/mysql

  spring_app:
    image: oumayma2/devopsproject
    container_name: devopscontainer
    restart: on-failure
    ports:
      - 9091:9091
    depends_on:
      - mysqldb