version: '3'
services:
  # Service MySQL
  mysql:
    image: mysql:8.0
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: devopsfarouk
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - sql_network

  # Service Spring Boot
  spring-boot-app:
    build:
      context: .
    container_name: container_spring
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/devopsfarouk
    depends_on:
      - mysql
    volumes:
        - spring-boot-app:/app
    networks:
        - sql_network
  web:
    build:
        context: .
    image: faroukmk07/devopsprojectfront:farouk
    ports:
          - "4200:4200"
    depends_on:
          - spring-boot-app
    networks:
          - sql_network
volumes:
  mysql-data:
  spring-boot-app:
networks:
  sql_network:
     driver: bridge
