version: "2"
services:
  backend:
    depends_on: [db]
    image: mohamedazizali/aziz:1.0
    ports:
      - "8089:8089"
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: devopsdb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306" #jw


